In [123]:
#Esercizio 1: Che tipo di struttura dati o matematica potrebbe rappresentare? 
#Come facciamo per accedere ad un elemento in particolare?

import numpy as np
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] #è una matrice con 3 righe e 5 colonne
mat_np = np.array(mat)

mat_np

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
#Per accedere ad un elemento in particolare:
print(mat_np[1,2])

7


In [13]:
#Esercizio 2: Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?
import math
print(math.sin(5))
print(math.cos(70))
print(math.factorial(4))
print(math.pi) #pigreco

-0.9589242746631385
0.6333192030862999
24
3.141592653589793


In [17]:
#Esercizio 3: Proviamo a eseguire math.degrees(math.pi) Qual è e cosa significa il risultato? 

math.degrees(math.pi) #Il risultato è 180 e significa che π radianti corrispondono a 180 gradi (serve a convertire radianti in gradi)



Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [30]:
#Esercizio 3: L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno.
#Rispondiamo alle domande del CEO della Object SpA: 
#• qual è stata la vendita massima mensile? E quella minima? 
#• quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono? 
#• quali sono le vendite minori di 3000 oggetti?
#• in media quanti oggetti sono stati venduti al mese?

lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
vendite = np.array(lst)

print(vendite.max()) #vendita massima mensile
print(vendite.min()) #vendita minima mensile

filtro_1 = vendite > 4999
print(vendite[filtro_1], len(vendite[filtro_1])) #vendite mensili >4999 e quante sono

filtro_2 = vendite < 3000
print(vendite[filtro_2]) #vendite mensili <3000

vendite.mean() #vendite medie

8150
1280
[5500 7200 6410 8150 7100 5350] 6
[2000 1280 1900 2500]


4634.166666666667

In [125]:
#Esercizio 4: Possiamo accedere alle stesse informazioni nello stesso modo: fatturati_dict[1997] fatturati_series[1997] 
#Dunque qual è la differenza tra i due tipi di dato? 
#Cosa potremmo fare con la Series che non possiamo fare con il dizionario?

import pandas as pd

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [43]:
#Esercizio 5: L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray.  
#L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: •con un ciclo for •con il masking

import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

print(stipendi * 2) #raddoppio gli sitpendi con il masking

stipendi_doppi = []
for stipendio in stipendi:  
    doppio = stipendio * 2  #raddoppio gli stipendi con ciclo for
    stipendi_doppi.append(doppio)
print(stipendi_doppi)

[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [56]:
#Esercizio 6: Scrivere un programma che, data una lista di numeri, fornisca in output i tre numeri più grandi;
#gestire il caso in cui la lista sia più corta di tre, e quando uno o più dei numeri selezionati sono uguali.

lista = [20, 40, 60, 40, 100, 10] #lista con valori tutti diversi
lista.sort(reverse = True)
print(lista[0:3])

lista2 = [85, 12]
lista2.sort(reverse = True) #lista con meno di 3 valori
print(lista2[0:3])

lista3 = [100, 50, 100, 30, 100, 75] #lista con numeri uguali
lista3.sort(reverse = True)
print(lista3[0:3])

[100, 60, 40]
[85, 12]
[100, 100, 100]


In [66]:
#Esercizio 7: Scrivere un programma che 
#• in input acquisisce una lista di numeri e un numero K 
#• in output, dovrà restituire la media di tutti i numeri nella lista maggiori o uguali a K 
#• se non ce ne dovesse essere nessuno, dovrà stampare a schermo un messaggio adeguato.

import numpy as np 
numeri = np.array([12, 3, 18, 7, 25, 9, 14, 6, 20, 4])
K = int(input("Inserisci K: "))

numeri_filtrati = numeri[numeri >= K]
if len(numeri_filtrati) == 0:
    print("Non ci sono valori maggiori o uguali a", K)
else:
    print("La media è: ", numeri_filtrati.mean())

Inserisci K:  30


Non ci sono valori maggiori o uguali a 30


In [69]:
#Esercizio 8: Scrivere un programma che, data una lista di numeri, come output stamperà lo stesso numero di asterischi su righe diverse, 
#ottenendo una semplice visualizzazione grafica.

numeri = [10, 5, 8, 2, 12, 1, 6]
for numero in numeri:
          print(numero, "=", "*" * numero)

10 = **********
5 = *****
8 = ********
2 = **
12 = ************
1 = *
6 = ******


In [94]:
#Esercizio 9: Trovare i codici fiscali che contengono "95", metterli in una lista, e alla fine stamparla; 
#• inoltre, per ognuno di essi, stampare a video i caratteri relativi al nome e quelli relativi al cognome.

lista_cf = ["ABCDEF95G01A123B", "GHIJKL91M02A321C", "MNOPQR89S03A456D", "STUVWX95Z04A654E", "XYZABC01D05A789F", "DEFGHI95J06A987G"]
cf_95 = []

for cf in lista_cf:
    if "95" in cf:
        cf_95.append(cf)
print(cf_95)

for cf95 in cf_95:
    cognome = cf95[0:3]
    nome = cf95[3:6]
    print(cf95, "-", "Cognome:", cognome, "Nome:", nome)

['ABCDEF95G01A123B', 'STUVWX95Z04A654E', 'DEFGHI95J06A987G']
ABCDEF95G01A123B - Cognome: ABC Nome: DEF
STUVWX95Z04A654E - Cognome: STU Nome: VWX
DEFGHI95J06A987G - Cognome: DEF Nome: GHI


In [92]:
#Esercizio 10: Abbiamo tre liste della stessa lunghezza, dove ogni elemento nella medesima posizione si riferisce ai dati dello stesso studente: 
#• Stampare a video tutti e solo gli studenti che frequentano una prima edizione; non tutti i dati potrebbero essere necessari.

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry"] 
corsi = ["Cybersecurity", "Data Analyst", "Backend", "Frontend", "Data Analyst", "Backend", "Frontend", "Cybersecurity"] 
edizioni = [1, 2, 3, 2, 2, 1, 3, 3]

studenti_edizioni = {}
for i in range(len(studenti)):
    studenti_edizioni[studenti[i]]=edizioni[i]

for studenti, edizioni in studenti_edizioni.items():
    if edizioni == 1:
        print(studenti)




Alex
Faith


In [99]:
#Esercizio 11: Abbiamo una lista di stringhe di prezzi in dollari, che erroneamente sono stati scritti con il simbolo dell'euro.
#Cambiare il simbolo dell'euro (€) in quello del dollaro ($) per ogni stringa nella lista; il risultato sarà memorizzato in un'altra lista.

prezzi = ["100 €", "200 €", "500 €", "10 €", "50 €", "70 €"]
prezzi_dollaro = []

for prezzo in prezzi:
    prezzo_dollaro = prezzo.replace("€", "$")
    prezzi_dollaro.append(prezzo_dollaro)

print(prezzi_dollaro)

['100 $', '200 $', '500 $', '10 $', '50 $', '70 $']


In [106]:
#Esercizio 12: Abbiamo una lista di studenti. Vogliamo dividere gli studenti in due squadre per un campionato di Uno nel seguente modo: 
#selezioneremo i nomi in posizione pari per un squadra, e i nomi in posizione dispari per l'altra. 
#Creiamo due liste per ogni squadra, e alla fine visualizziamole.

studenti = ["Alex", "Bob", "Cindy", "Dan", "Emma", "Faith", "Grace", "Henry", "Isabelle", "John"]
pari = studenti[0::2]
dispari = studenti[1::2]

print("Squadra A: ", pari)
print("Squadra B: ", dispari)


Squadra A:  ['Alex', 'Cindy', 'Emma', 'Grace', 'Isabelle']
Squadra B:  ['Bob', 'Dan', 'Faith', 'Henry', 'John']


In [126]:
#Esercizio 13: Abbiamo una lista con i guadagni degli ultimi 12 mesi (supponiamo da Gennaio a Dicembre).
#Dobbiamo confrontare, stampando tutto a video, il guadagno di ogni mese con la media dei guadagni precedenti, 
#e specificare nell'output se il guadagno attuale è maggiore o minore della media dei precedenti. 
#Esempio di un possibile output: 
#Mese 1: 100 € 
#Mese 2: 90 € (media prec: 100 € - il guadagno attuale è minore) 
#Mese 3: 70 € (media prec: 95 € - il guadagno attuale è minore)

import numpy as np
guadagni = np.array([100, 90, 70, 40, 50, 80, 90, 120, 80, 20, 50, 50])

for i in range(len(guadagni)):
    guadagno_attuale = guadagni[i]

    if i == 0:
        print("Mese", i+1, guadagno_attuale, "€")
    else:
        precedenti = guadagni[0:i]
        media_precedenti = precedenti.mean()
        #print("Mese", i+1, guadagno_attuale, "€", "media prec: ", media_precedenti,"€")
        if guadagno_attuale > media_precedenti:
            print("Mese", i+1, guadagno_attuale, "€", "media prec: ", media_precedenti,"€", "- il guadagno attuale è maggiore")
        elif guadagno_attuale == precedenti.mean():
            print("Mese", i+1, guadagno_attuale, "€", "media prec: ", media_precedenti,"€", "- il guadagno attuale è uguale")
        else:
            print("Mese", i+1, guadagno_attuale, "€", "media prec: ", media_precedenti,"€", "- il guadagno attuale è minore")


    
   


Mese 1 100 €
Mese 2 90 € media prec:  100.0 € - il guadagno attuale è minore
Mese 3 70 € media prec:  95.0 € - il guadagno attuale è minore
Mese 4 40 € media prec:  86.66666666666667 € - il guadagno attuale è minore
Mese 5 50 € media prec:  75.0 € - il guadagno attuale è minore
Mese 6 80 € media prec:  70.0 € - il guadagno attuale è maggiore
Mese 7 90 € media prec:  71.66666666666667 € - il guadagno attuale è maggiore
Mese 8 120 € media prec:  74.28571428571429 € - il guadagno attuale è maggiore
Mese 9 80 € media prec:  80.0 € - il guadagno attuale è uguale
Mese 10 20 € media prec:  80.0 € - il guadagno attuale è minore
Mese 11 50 € media prec:  74.0 € - il guadagno attuale è minore
Mese 12 50 € media prec:  71.81818181818181 € - il guadagno attuale è minore
